-- Migration: 014_memory_hybrid_schema.sql
-- Epic: SOLARIA Memory System - Híbrida
-- Task: DFO-233 - Diseñar schema de base de datos para memoria híbrida
-- Author: ECO-Lambda | Memory System Implementation
-- Date: 2026-01-06
--
-- Creates tables for hybrid memory system:
-- - memory_machines: Registered edge machines (claude-mem instances)
-- - memory_observations_remote: Central storage of observations from all machines
-- - memory_summaries_remote: Session summaries with embeddings
-- - memory_sync_log: Sync operation tracking
-- - memory_context_injections: Context injection tracking
--

-- =============================================================================
-- Table: memory_machines
-- =============================================================================
-- Registers edge machines running claude-mem
-- Each machine has a unique ID and sync metadata
--

CREATE TABLE IF NOT EXISTS memory_machines (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Machine Identification
  machine_id TEXT UNIQUE NOT NULL COMMENT 'Unique machine identifier (UUID)',
  machine_name VARCHAR(255) COMMENT 'Human-readable machine name (e.g., MacBook Pro Carlos)',

  -- Tracking
  first_seen_at TIMESTAMPTZ DEFAULT NOW() COMMENT 'First sync from this machine',
  last_sync_at TIMESTAMPTZ COMMENT 'Last successful sync timestamp',
  active BOOLEAN DEFAULT true COMMENT 'Whether machine is actively syncing',

  -- Statistics
  total_observations INT DEFAULT 0 COMMENT 'Total observations synced from this machine',
  total_syncs INT DEFAULT 0 COMMENT 'Total sync operations',
  last_sync_status ENUM('success', 'partial', 'failed') NULL COMMENT 'Status of last sync',

  -- Metadata
  metadata JSONB COMMENT 'Additional metadata (OS, IP, version, etc.)',

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW() ON UPDATE NOW()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Indexes
CREATE INDEX idx_machines_active ON memory_machines(active);
CREATE INDEX idx_machines_last_sync ON memory_machines(last_sync_at DESC);

-- =============================================================================
-- Table: memory_observations_remote
-- =============================================================================
-- Central storage of tool usage observations from all edge machines
-- Each observation represents a tool call (read, write, edit, etc.)
--

CREATE TABLE IF NOT EXISTS memory_observations_remote (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Machine Context
  machine_id TEXT NOT NULL COMMENT 'Source machine ID (from memory_machines)',
  local_observation_id INTEGER NOT NULL COMMENT 'Original observation ID in local SQLite',

  -- Session Context
  session_id TEXT NOT NULL COMMENT 'OpenCode session ID',
  project TEXT COMMENT 'Project name (e.g., SOLARIA-DFO, Akademate)',

  -- Tool Information
  tool_name VARCHAR(100) NOT NULL COMMENT 'Tool name (read, write, edit, create, etc.)',
  tool_input JSONB COMMENT 'Tool input parameters',
  tool_output JSONB COMMENT 'Tool response/output',

  -- Vector Search Support
  embedding VECTOR(1536) COMMENT 'Embedding for semantic search (OpenAI text-embedding-ada-002)',
  text_content TEXT COMMENT 'Extracted text for embedding generation',

  -- Metadata
  metadata JSONB COMMENT 'Additional metadata (file, line, duration, etc.)',

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL COMMENT 'When observation was created (local time)',
  synced_at TIMESTAMPTZ DEFAULT NOW() COMMENT 'When observation was synced to central DB',

  -- References
  CONSTRAINT fk_machine FOREIGN KEY (machine_id)
    REFERENCES memory_machines(machine_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Indexes for efficient queries
CREATE INDEX idx_remote_machine ON memory_observations_remote(machine_id);
CREATE INDEX idx_remote_session ON memory_observations_remote(session_id);
CREATE INDEX idx_remote_project ON memory_observations_remote(project);
CREATE INDEX idx_remote_created ON memory_observations_remote(created_at DESC);
CREATE INDEX idx_remote_tool ON memory_observations_remote(tool_name);

-- Vector search index (requires pgvector extension)
-- CREATE INDEX idx_remote_embedding ON memory_observations_remote USING ivfflat(embedding vector_cosine_ops);

-- =============================================================================
-- Table: memory_summaries_remote
-- =============================================================================
-- Session summaries generated by AI agents
-- Compressed representation of session activity
--

CREATE TABLE IF NOT EXISTS memory_summaries_remote (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Session Identification
  session_id TEXT UNIQUE NOT NULL COMMENT 'OpenCode session ID',
  project TEXT NOT NULL COMMENT 'Project name',

  -- Summary Content
  summary TEXT NOT NULL COMMENT 'AI-generated session summary',
  key_points TEXT[] COMMENT 'Array of key decisions/action items',
  tags TEXT[] COMMENT 'Array of descriptive tags',
  observations_count INTEGER DEFAULT 0 COMMENT 'Number of observations in this session',

  -- Machine Context
  machine_id TEXT COMMENT 'Machine that generated this summary',

  -- Vector Search Support
  embedding VECTOR(1536) COMMENT 'Summary embedding for semantic search',

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW() COMMENT 'When summary was generated',
  updated_at TIMESTAMPTZ DEFAULT NOW() ON UPDATE NOW()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Indexes
CREATE INDEX idx_summary_session ON memory_summaries_remote(session_id);
CREATE INDEX idx_summary_project ON memory_summaries_remote(project);
CREATE INDEX idx_summary_created ON memory_summaries_remote(created_at DESC);

-- Vector search index
-- CREATE INDEX idx_summary_embedding ON memory_summaries_remote USING ivfflat(embedding vector_cosine_ops);

-- =============================================================================
-- Table: memory_sync_log
-- =============================================================================
-- Logs all sync operations between edge machines and central DB
-- Used for monitoring, debugging, and statistics
--

CREATE TABLE IF NOT EXISTS memory_sync_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Machine Context
  machine_id TEXT NOT NULL COMMENT 'Machine that performed sync',

  -- Sync Operation Details
  sync_type ENUM('batch', 'manual', 'session_end') NOT NULL COMMENT 'Type of sync operation',

  -- Statistics
  observations_count INTEGER DEFAULT 0 COMMENT 'Number of observations synced',
  summaries_count INTEGER DEFAULT 0 COMMENT 'Number of summaries synced',
  sync_duration_ms INTEGER COMMENT 'Sync operation duration in milliseconds',

  -- Status
  status ENUM('success', 'partial', 'failed') NOT NULL COMMENT 'Overall sync status',
  error_message TEXT COMMENT 'Error details if status is failed',

  -- Details
  details JSONB COMMENT 'Additional sync details (bytes transferred, etc.)',

  -- Timestamp
  created_at TIMESTAMPTZ DEFAULT NOW()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Indexes
CREATE INDEX idx_sync_machine ON memory_sync_log(machine_id);
CREATE INDEX idx_sync_status ON memory_sync_log(status);
CREATE INDEX idx_sync_created ON memory_sync_log(created_at DESC);

-- =============================================================================
-- Table: memory_context_injections
-- =============================================================================
-- Tracks context injections into OpenCode sessions
-- Used to analyze how memory is being used
--

CREATE TABLE IF NOT EXISTS memory_context_injections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Target Session
  target_session_id TEXT COMMENT 'OpenCode session that received context',
  project TEXT COMMENT 'Project of target session',

  -- Source Context
  source_observations UUID[] COMMENT 'Array of observation IDs that were injected',
  source_summaries UUID[] COMMENT 'Array of summary IDs that were injected',

  -- Statistics
  injection_count INTEGER DEFAULT 0 COMMENT 'Total items injected',
  machine_count INTEGER DEFAULT 0 COMMENT 'Number of unique machines in injection',

  -- Effectiveness Metrics
  was_used BOOLEAN DEFAULT false COMMENT 'Whether injected context was actually used',
  effectiveness_score DECIMAL(3,2) COMMENT 'User-rated effectiveness (1.0-5.0)',

  -- Timestamp
  created_at TIMESTAMPTZ DEFAULT NOW()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Indexes
CREATE INDEX idx_injection_session ON memory_context_injections(target_session_id);
CREATE INDEX idx_injection_project ON memory_context_injections(project);
CREATE INDEX idx_injection_created ON memory_context_injections(created_at DESC);

-- =============================================================================
-- Migration Complete
-- =============================================================================

-- Log migration
INSERT INTO activity_logs (
  project_id, action, details, category, level
) VALUES (
  1,
  'migration_applied',
  'Migration 014_memory_hybrid_schema.sql: Created tables for hybrid memory system',
  'database',
  'info'
);
