#!/usr/bin/env bash
set -euo pipefail

#
# Ingest a project/milestones into the SOLARIA Field Operations database
# Usage: bash scripts/ingest-project.sh "Project Name" /path/to/milestones.md
#

# Load environment variables from .env if available
source "$(dirname "$0")/../.env" 2>/dev/null || true

# Configuration with defaults
CONTAINER=${CONTAINER:-"solaria-digital-field--operations-office-1"}
DB_ROOT_PASS="${MYSQL_ROOT_PASSWORD:-SolariaRoot2024}"
DB_NAME="${DB_NAME:-solaria_construction}"

# Validate arguments
if [ $# -lt 2 ]; then
  echo "Usage: $0 <project_name> <milestones_file>"
  echo "Example: $0 'My Project' ./milestones.md"
  exit 1
fi

PROJECT_NAME="$1"
MILESTONES_FILE="$2"

# Validate milestones file exists
if [ ! -f "$MILESTONES_FILE" ]; then
  echo "Error: Milestones file not found: $MILESTONES_FILE"
  exit 1
fi

# Check if container is running using proper name matching
echo "[ingest] Checking if container '${CONTAINER}' is running..."
if ! docker ps --format "{{.Names}}" | grep -q "^${CONTAINER}$"; then
  echo "Error: Container '${CONTAINER}' is not running"
  echo ""
  echo "Available containers:"
  docker ps --format "{{.Names}}"
  echo ""
  echo "Hint: You can set a custom container name with:"
  echo "  CONTAINER=<name> bash $0 \"$PROJECT_NAME\" \"$MILESTONES_FILE\""
  exit 1
fi

echo "[ingest] Container found and running"

# Parse milestones file and generate SQL
echo "[ingest] Parsing milestones from: $MILESTONES_FILE"

# Create temporary SQL file
SQL_FILE=$(mktemp /tmp/ingest-XXXXXX.sql)
trap "rm -f $SQL_FILE" EXIT

# Start SQL transaction
cat > "$SQL_FILE" <<EOSQL
-- Auto-generated by ingest-project.sh
-- Project: ${PROJECT_NAME}
-- Source: ${MILESTONES_FILE}

START TRANSACTION;

-- Insert or update project
INSERT INTO projects (name, description, status, created_at, updated_at)
VALUES ('${PROJECT_NAME}', 'Imported from ${MILESTONES_FILE}', 'active', NOW(), NOW())
ON DUPLICATE KEY UPDATE updated_at = NOW();

SET @project_id = (SELECT id FROM projects WHERE name = '${PROJECT_NAME}' LIMIT 1);

EOSQL

# Parse milestones from markdown file
# Expects format: ## Milestone Name or - [ ] Task name
MILESTONE_COUNT=0
TASK_COUNT=0

while IFS= read -r line; do
  # Match milestone headers (## Milestone Name)
  if [[ "$line" =~ ^##[[:space:]]+(.+)$ ]]; then
    MILESTONE_NAME="${BASH_REMATCH[1]}"
    # Escape single quotes for SQL
    MILESTONE_NAME="${MILESTONE_NAME//\'/\'\'}"
    ((MILESTONE_COUNT++))
    cat >> "$SQL_FILE" <<EOSQL

-- Milestone: ${MILESTONE_NAME}
INSERT INTO milestones (project_id, name, status, created_at)
SELECT @project_id, '${MILESTONE_NAME}', 'pending', NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM milestones WHERE project_id = @project_id AND name = '${MILESTONE_NAME}'
);
SET @milestone_id = (SELECT id FROM milestones WHERE project_id = @project_id AND name = '${MILESTONE_NAME}' LIMIT 1);
EOSQL
  fi

  # Match tasks (- [ ] Task name or - [x] Task name)
  if [[ "$line" =~ ^[[:space:]]*-[[:space:]]*\[([[:space:]x])\][[:space:]]+(.+)$ ]]; then
    TASK_STATUS="${BASH_REMATCH[1]}"
    TASK_NAME="${BASH_REMATCH[2]}"
    # Escape single quotes for SQL
    TASK_NAME="${TASK_NAME//\'/\'\'}"

    if [[ "$TASK_STATUS" == "x" ]]; then
      STATUS="completed"
    else
      STATUS="pending"
    fi

    ((TASK_COUNT++))
    cat >> "$SQL_FILE" <<EOSQL
INSERT INTO tasks (milestone_id, title, status, created_at)
SELECT @milestone_id, '${TASK_NAME}', '${STATUS}', NOW()
WHERE @milestone_id IS NOT NULL AND NOT EXISTS (
  SELECT 1 FROM tasks WHERE milestone_id = @milestone_id AND title = '${TASK_NAME}'
);
EOSQL
  fi
done < "$MILESTONES_FILE"

# Finish SQL transaction
cat >> "$SQL_FILE" <<EOSQL

COMMIT;

-- Summary
SELECT 'Import completed' as status,
       (SELECT COUNT(*) FROM projects WHERE name = '${PROJECT_NAME}') as projects,
       (SELECT COUNT(*) FROM milestones WHERE project_id = @project_id) as milestones,
       (SELECT COUNT(*) FROM tasks t JOIN milestones m ON t.milestone_id = m.id WHERE m.project_id = @project_id) as tasks;
EOSQL

echo "[ingest] Generated SQL with $MILESTONE_COUNT milestones and $TASK_COUNT tasks"

# Execute SQL directly using docker exec -i
echo "[ingest] Executing SQL in container..."
docker exec -i "${CONTAINER}" mariadb -uroot -p"${DB_ROOT_PASS}" "${DB_NAME}" < "$SQL_FILE"

echo "[ingest] Successfully imported project '${PROJECT_NAME}'"
echo "[ingest] Milestones: $MILESTONE_COUNT"
echo "[ingest] Tasks: $TASK_COUNT"
